name: Create ZIP archives
on: [push]
jobs:
  To-Zip:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create zip archivec from dirs
        run: ./make-zip.sh

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: '["*.zip"]'
          message: 'github action: autobuild zip files after push'
          push: 'origin master --force'