name: Create ZIP archives
on: [push]
jobs:
  To-Zip:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create map-osm-and-svg.zip
        run: ./make-zip.sh map-osm-and-svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: '["*.zip"]'
          message: 'Autobuild zip files after push'
          push: true