name: Create ZIP archives
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create map-osm-and-svg.zip
        run: ./make-zip.sh map-osm-and-svg

      - name: Upload all zip archives.
        uses: actions/upload-artifact@v3
        with:
          name: zip-archives
          path: "*.zip"